const data = {
  "Relievi i lartë": "Zona me male dhe kodra të theksuara, si Mali i Dajtit (1,613 m), malet e Shëngjergjit dhe Elbasanit.",
  "Relievi i ulët": "Zona fushore dhe bregdetare në perëndim, si Ultësira Bregdetare dhe fushat e Myzeqesë.",
  "Mikroklimat": "Ndryshime të vogla klimatike në zona të ndryshme, p.sh., më shumë lagështi në bregdet dhe më shumë reshje në zona malore.",
  "Principata e Kastriotëve": "Shtet mesjetar shqiptar i udhëhequr nga familja Kastrioti, me kryeqytet Krujën.",
  "Betejat e Skënderbeut": "Betejat e Tiranës (1462), Vajkalit (1465), dhe Mollës së Kuqe janë disa nga fitoret kundër osmanëve.",
  "Skënderbeu": "Gjergj Kastrioti, heroi kombëtar shqiptar, udhëheqës i rezistencës kundër Perandorisë Osmane.",
  "Karl Topia": "Sundimtar shqiptar i shekullit XIV, që drejtoi Durrësin dhe mbrojti qytetin nga sulmet e huaja.",
  "Ikonografia e Elbasanit": "Traditë artistike e pikturimit të ikonave fetare me ngjyra të ndezura dhe motive të pasura.",
  "Punimi i drurit": "Mjeshtëri tradicionale në gdhendjen e drurit për mobilie, dyer dhe objekte artistike.",
  "Muzika qytetare": "Stil muzikor tradicional me melodi të ëmbla dhe ritme të ngadalta, shpesh me instrumente tradicionale.",
  "Qeleshja": "Kapelë tradicionale e bardhë prej leshi e burrave shqiptarë.",
  "Shamia e bardhë/kuqe": "Simbol përdorur nga gratë shqiptare për të treguar statusin martesor ose familjar.",
  "Flija": "Pjatë tradicionale me petë të holla të lyera me ajkë dhe të pjekura në saç.",
  "Kaçamaku": "Gatim me miell misri, shpesh i shoqëruar me djathë ose kos.",
  "Mishi i thatë": "Mish i ruajtur përmes tharjes dhe kriposjes.",
  "Byreku": "Pjatë me petë të mbushura me përbërës të ndryshëm si mish, kungull ose djathë.",
  "Hallva me miell misri": "Ëmbëlsirë tradicionale shqiptare e bërë me miell misri dhe sheqer.",
  "Tullumëza": "Ëmbëlsira të vogla të skuqura dhe të zhytura në sherbet.",
  "Bejtexhinjtë": "Poetë shqiptarë të shekujve XVIII–XIX me ndikime orientale.",
  "Nezim Frakulla dhe Hasan Zyko Kamberi": "Poetë bejtexhinj që trajtonin tema fetare, dashurie dhe satirike.",
  "Legjenda e Vorrit të Ashikut": "Tregim për një çift të dashuruarish që u vetëvranë për shkak të hasmërisë.",
  "Legjenda e Syrit të Ciklopit": "Përrallë për një përbindësh njësysh në Shkëmbin e Kavajës.",
  "Shqipëria e Jugut": "Rajon i pasur me natyrë, histori dhe kulturë.",
  "Qytetet kryesore të Jugut": "Berati, Gjirokastra, Vlorë, Saranda.",
  "Berati": "Qytet i njohur për kalatë dhe shtëpitë tradicionale.",
  "Gjirokastra": "Qytet me shtëpi të ndërtuara në stilin tipik të jugut.",
  "Vlorë": "Qytet bregdetar historik me rëndësi strategjike.",
  "Saranda": "Qytet turistik i njohur për plazhet dhe turizmin.",
  "Kultura popullore": "Tradita, zakone dhe veprimtari që përfaqësojnë jetën popullore.",
  "Monumentet e kulturës": "Objekte me vlera të larta historike dhe kulturore.",
  "Figura historike": "Individë që kanë ndikuar në historinë shqiptare.",
  "Etnografia": "Studimi i zakoneve dhe kulturës së komuniteteve.",
  "Zeje tradicionale": "Profesione dhe mjeshtëri të trashëguara në komunitete.",
  "Dibrë": "Qytet me rëndësi në kulturën dhe historinë shqiptare.",
  "Lumi Vjosë": "Lumi më i gjatë në jug, i njohur për natyrën e tij.",
  "Monument i kulturës": "Objekte historike me vlera të veçanta.",
  "Kujtesa historike": "Ngjarje dhe përvoja që mbeten në memorien kolektive.",
  "Dajti": "Mal popullor për piknik dhe turizëm në natyrë.",
  "Përpunimi i ullirit": "Industri tradicionale për prodhimin e vajit të ullirit.",
  "Gliko": "Ëmbëlsirë me fruta e përgatitur në jug të Shqipërisë.",
  "Festat tradicionale": "Ngjarje dhe zakone që festohen rregullisht.",
  "Dita e Verës": "Festë e mesit të marsit që simbolizon ardhjen e pranverës.",
  "Pite me lakra": "Ushqim tradicional shqiptar me brumë dhe lakra.",
  "Pasuritë natyrore": "Burime që ndihmojnë zhvillimin ekonomik e social.",
  "Monumente natyrore": "Forma dhe vende të mbrojtura për bukurinë e tyre.",
  "Kultura tradicionale": "Kultura që ka kaluar brez pas brezi në një komunitet.",
  "Arkeologjia": "Shkenca që studion objekte dhe mbetje të lashta.",
  "Shkumbini": "Lumi që ndan Shqipërinë e Jugut dhe të Mesme.",
  "Hidrocentrali": "Instalacion që prodhon energji përmes ujit.",
  "Pozita Gjeografike": "Vendndodhja e një shteti, kufijtë dhe rëndësia strategjike.",
  "Relievi": "Forma të ndryshme të terrenit si male, fusha e kodra.",
  "Klima": "Kushtet atmosferike të një rajoni.",
  "Pasuria Kulturore": "Trashëgimia artistike, arkitekturore dhe shpirtërore.",
  "Monumentet": "Ndërtesa historike si kalatë dhe kullat me vlerë kulturore.",
  "Veshjet Tradicionale": "Rroba që pasqyrojnë identitetin kulturor të zonës.",
  "Mikpritja": "Tradita shqiptare e pritjes me nder dhe bujari.",
  "Kanuni i Lekë Dukagjinit": "Kod zakonor që rregullon jetën e veriut shqiptar.",
  "Muzika Epike": "Këngë për heroizma dhe histori të shoqëruara me lahutë.",
  "Vallëzimi": "Lëvizje tradicionale si Vallja e Logut në veri.",
  "Arti": "Forma artistike si piktura, skulptura dhe arkitektura tradicionale.",
  "Artizanati": "Punime me dorë që përfshijnë qilima dhe vegla muzikore.",
  "Folklori": "Legjenda dhe tregime popullore shqiptare.",
  "Gjuha Gegë": "Dialekti i veriut të Shqipërisë.",
  "Kuzhina Tradicionale": "Ushqime si flija dhe kaçamaku që përfaqësojnë traditat kulinare.",
  "Byrekët dhe Brumat": "Ushqime si byreku dhe piteja e përgatitur me brumë.",
  "Ëmbëlsirat": "Hallva, tullumëza dhe gliko si pjesë e kuzhinës tradicionale.",
  "Letërsia Gojorë": "Tregime dhe histori të trashëguara përmes rrëfimeve gojore.",
   "Fshatrat tradicionale": "Zona ku mbijetojnë ndërtimet dhe zakonet e lashta, si fshatrat e Dukatës dhe të Pazhokut.",
"Qytetet historike": "Qytetet me vlera të jashtëzakonshme për historinë dhe kulturën shqiptare, si Shkodra dhe Elbasani.",
"Ritualet fetare": "Ceremonitë tradicionale fetare që shoqërojnë jetën shpirtërore, si martesa dhe varrosja.",
"Shpella e Treniçit": "Një shpella e lashtë që ka luajtur rol të rëndësishëm në mitologjinë dhe historiografinë shqiptare.",
"Mitologjia shqiptare": "Bota e miteve dhe legjendave që pasqyrojnë besimet dhe kulturën popullore shqiptare.",
"Ndërtimi i kalave": "Mjeshtëri në ndërtimin e kalave, të tilla si Kalaja e Krujës dhe Kalaja e Shkodrës.",
"Shpirti i natyrës": "Besimi që natyra ka një shpirt dhe është e lidhur me jetën e njerëzve.",
"Përpunimi i leshit": "Tradita e përpunimit të leshit për të bërë rroba dhe produkte të tjera tradicionale.",
"Artizanati i thurjes": "Mjeshtëri që përfshin thurjen e qilimave dhe tekstileve të tjera me motivet tradicionale.",
"Pamja e pasurisë natyrore": "Vlerësimi i pasurisë natyrore të Shqipërisë, që pasqyron pasurinë e biodiversitetit dhe ekosistemit.",
"Vezhtimi i mjaltit": "Profesioni i tradicionale i prodhimit të mjaltit nga bletët, veçanërisht në zonat malore.",
"Festat e Beratit": "Një seri ngjarjesh tradicionale që pasqyrojnë historinë dhe kulturën e qytetit të Beratit.",
"Veshjet e pasura të jugut": "Kostume tradicionale të pasura me ngjyra dhe që kanë një histori të veçantë në Shqipërinë jugore.",
"Rapsoditë dhe baladat": "Këngë epike dhe balada që përshkruajnë heronj dhe ngjarje historike.",
"Tregtarët e lashtë": "Tregtarët që kanë udhëtuar dhe kanë sjellë ndikime nga kulturat e huaja në Shqipëri.",
"Qëndisma": "Procesi i endjes së fijeve të leshit për të krijuar materiale për veshje dhe mbulesa.",
"Tradita e luajtjes me zhurmë": "Një lojë tradicionale që përfshin muzikë dhe ritme të ndryshme për të shoqëruar ngjarje festive.",
"Lufta për mbrojtjen e identitetit": "Përpjekjet e shqiptarëve për të ruajtur traditat dhe identitetin kombëtar përballë ndikimeve të huaja.",
"Simbolet e trashëgimisë kulturore": "Elementët e kulturës shqiptare që mbartin vlera të veçanta për brezat e ardhshëm.",
"Kriza e kulturës popullore": "Ndryshimet që kanë ndodhur në kulturën popullore shqiptare gjatë periudhave të ndryshme historike.",
"Festa e Gjirokastrës": "Ngjarje kulturore që pasqyron traditat dhe kulturën e Gjirokastrës.",
"Thurja e ullishtes": "Mjeshtëri tradicionale që përfshin mbjelljen dhe kujdesin për ullinjtë.",
"Shtegu i Dajti": "Rruga malore që të çon në majën e Dajti, e njohur për pamjet mahnitëse.",
"Vajti në kishë": "Ceremonitë e ndjekura nga besimtarët në Shqipëri, veçanërisht në veriun e vendit.",
"Druri i Zinxhirit": "Një lloj druri që përdoret për të bërë pajisje dhe vegla tradicionale.",
"Veprat e pikturës shqiptare": "Krijimet artistike që pasqyrojnë jetën dhe kulturën e shqiptarëve.",
"Logu i Kastriotëve": "Një strukturë mbrojtëse që ndihmoi në mbrojtjen e principatës së Kastriotëve.",
"Festa e Punëtorëve të Qumështit": "Ngjarje që kremton traditën e prodhimit të produkteve të qumështit.",
"Shpirti i kombit": "Besimi në forcën shpirtërore që bashkon popullin shqiptar.",
"Folklori i veriut": "Elemente të folklorit që kanë lindur dhe janë zhvilluar në zonat veriore të Shqipërisë.",
"Traditat e Pashkëve": "Ritualet dhe zakonet që shoqërojnë festën e Pashkëve në Shqipëri.",
"Ushqimet e malësorëve": "Pjatat tradicionale që përgatiten nga popullsia malësore.",
"Motivi i drerit": "Një simbol i njohur në artin dhe tekstilet tradicionale shqiptare.",
"Burimi i Shkumbinit": "Vendi ku lind lumi Shkumbin, një nga lumenjtë më të njohur në Shqipëri.",
"Zonat e trashëgimisë kulturore": "Vende dhe rajone që kanë ruajtur tradita dhe zakonet për breza të tërë.",
"Legjendat shqiptare": "Tregime që kanë kaluar brez pas brezi dhe pasqyrojnë historinë e Shqipërisë.",
"Blerja e thesarëve": "Aktiviteti i grumbullimit të sendeve të vlefshme që pasqyrojnë kulturën shqiptare.",
"Tradita e xhubletës": "Një veshje tradicionale e grave shqiptare, e njohur për thurjen e saj të veçantë.",
"Simbolika e shqiponjës": "Një nga simbolet më të njohura të kulturës shqiptare, shpesh përdorur në flamuj dhe stema.",
"Festat e krishtlindjeve": "Festimet që lidhen me lindjen e Krishtit, me rituale dhe zakone të veçanta.",
"Zonat me ndikime turke": "Rajone ku ndikimet e Perandorisë Osmane janë më të theksuara në kulturën dhe arkitekturën lokale.",
"Rrëfimet e vjetra": "Tregime gojore që pasqyrojnë jetën dhe historinë e njerëzve në Shqipëri.",
"Kufijtë natyrorë": "Zona ku natyra ka krijuar kufij të natyrshëm që ndihmojnë në ndarjen e rajoneve.",
"Festa e Bajramit": "Një nga festat më të rëndësishme për muslimanët shqiptarë, që kremtohet me familjen dhe miqtë.",
"Ritualet e martesës": "Ceremonitë tradicionale që shoqërojnë fejesën dhe martesën në Shqipëri.",
"Përpunimi i drurit të zi": "Përpunimi i lëndëve të drurit të veçantë për krijimin e sendeve tradicionale.",
"Shpirti i pasurisë kulturore": "Vlera që mbartin objektet dhe traditat për identitetin e shqiptarëve.",
"Festa e Shën Gjergjit": "Një festë popullore që përkujton shenjtorin dhe heronjtë e Shqipërisë.",
"Lufta për liri": "Përpjekjet e shqiptarëve për të mbrojtur pavarësinë dhe identitetin kombëtar.",
"Veshja e burrave të jugut": "Kostume tradicionale që përdoren nga burrat në jug të Shqipërisë.",
"Ritualet e ngjarjeve natyrore": "Ceremonitë dhe festat që pasqyrojnë kalimin e stinëve dhe ngjarje natyrore të tjera.",
"Pasuria e pikturës ikonografike": "Krijime artistike të karakterizuara nga ngjyra të forta dhe motive fetare.",
"Pajisjet e gjuetisë": "Veglat dhe armët tradicionale që përdoren për gjueti dhe mbrojtje.",
"Monumentet e natyrës": "Formacione të veçanta natyrore që janë shpallur si monumente dhe zona të mbrojtura.",
"Ritmet e folklorit shqiptar": "Lidhje të këngëve dhe vallëzimeve tradicionale me historinë dhe zakonet popullore.",
"Thurja e panarit": "Një proces i thurjes së materiale që përdoren për ndërtimin e kasolleve dhe strehueseve tradicionale.",
"Përpunimi i gështenjave": "Metoda tradicionale e përgatitjes së gështenjave për konsum dhe ruajtje.",
"Ushqimi i malësorëve": "Dieta tradicionale që përfshin mish, djathë, perime dhe produkte të tjera natyrale.",
"Qyteti i Apollonisë": "Një qytet i lashtë ilir, i njohur për rëndësinë e tij arkeologjike dhe historike.",
"Ritualet e natyrës dhe bletaria": "Tradita e bletarisë dhe përdorimi i mjaltit për mbrojtjen e shëndetit dhe ushqimin.",
"Monumentet e lashta arkeologjike": "Qytetet dhe kalatë që janë shpallur monumente historike për vlerat e tyre kulturore.",
"Kanuni i Shkodrës": "Një nga kodet zakonore që rregullon jetën shoqërore dhe familjare në zonën e Shkodrës.",
"Ngjarjet e historisë shqiptare": "Momente të rëndësishme të historisë që kanë ndikuar në formimin e identitetit shqiptar.",
"Ritualet e dasmës shqiptare": "Ceremonitë dhe zakonet që lidhen me dasmën në disa zona të Shqipërisë.",
"Vallëzimi i veriut": "Vallëzimi popullor i përdorur për të shoqëruar këngët dhe ngjarjet festash.",
"Traditat e dibranëve": "Zakone dhe praktika të ruajtura nga popullsia dibrane, një nga zonat më të pasura në kulturë.",
"Bashkëpunimi me fqinjët": "Ndërveprimet kulturore dhe historike të shqiptarëve me vendet përreth, veçanërisht me grekët dhe italianët.",
"Shtiza dhe fishekët": "Armatimi tradicional shqiptar, i përdorur për mbrojtjen dhe përgjakjen e territoreve të zonave malore.",
"Bajrami i veriut": "Një ngjarje festivale që kremton fitimet dhe mbrojtjen e traditave fetare në Shqipërinë veriore.",
"Pasuritë e kulturës shqiptare": "Vlera dhe trashëgimi kulturore që ndihmojnë në ruajtjen e identitetit kombëtar.",
"Zhvillimi i muzikës popullore": "Përhapja e muzikës popullore dhe instrumenteve tradicionale si lahuta dhe cemballo.",
"Ngjarje dhe tradita në fshatra": "Tradita dhe ngjarje që lidhen me jetën e përditshme në fshatrat shqiptare.",
"Qytetet e shekujve të kaluar": "Qytete që kanë pasur rëndësi në zhvillimin e kulturës dhe historisë shqiptare.",
"Pasaleli i Shkodrës": "Një ndër vendet më të njohura historike në Shkodër, që ka shërbyer si vend i adhurimeve fetare dhe kulturore.",
"Shkolla e Parë Shqipe": "Shkolla që ofronte mësim në gjuhën shqipe dhe luajti rol të rëndësishëm në zhvillimin e arsimit kombëtar.",
"Shkolla e Mësuesve në Elbasan": "Një nga shkollat më të rëndësishme të edukatës në Shqipëri, që ka kontribuar në mësimin dhe ruajtjen e gjuhës shqipe.",
"Kisha e Shën Ndout": "Një kishë e njohur për vlerat historike dhe kulturore që mbart, që ndodhet në zonën e Shkodrës.",
"Xhamia e Plumbit": "Një monument historik i qytetit të Shkodrës, i njohur për arkitekturën e saj unike dhe rëndësinë fetare.",
"Kala e Gjirokastrës": "Një nga kalatë më të njohura dhe të ruajtura të Shqipërisë, që ndodhet në qytetin e Gjirokastrës.",
"Qyteti i Apollonisë": "Një qytet i lashtë ilir që ka pasur rëndësi historike dhe kulturore për shqiptarët e antikitetit.",
"Qyteti i Durrësit": "Një nga qytetet më të lashta dhe të rëndësishme të Shqipërisë, me një histori të pasur dhe trashëgimi të thellë kulturore.",
"Rrëfimet e Malësisë": "Tradita gojore që përshkruan jetën dhe histori të banorëve të veriut të Shqipërisë.",
"Teza e Tiransë": "Një këndvështrim mbi historinë dhe zhvillimin e qytetit të Tiranës në periudha të ndryshme historike.",
"Mbishkrimi i Matit": "Një mbishkrim i lashtë që përmban të dhëna të rëndësishme mbi qytetërimin ilir.",
"Kultura e Dukatës": "Tradita dhe kultura e një zone të njohur për zhvillimin e bujqësisë dhe blegtorisë.",
"Tradita e veshjeve të Jugut": "Veshje tradicionale që përfaqësojnë karakteristikat kulturore dhe etnografike të jugut të Shqipërisë.",
"Kultura e Shkodrës": "Një trashëgimi kulturore e pasur që përfshin artin, muzikën dhe zakonet e qytetit të Shkodrës.",
"Kultura e Kosovës": "Traditat dhe zakonet e njohura në këtë rajon të Kosovës që pasqyrojnë identitetin shqiptar.",
"Kultura e Dukagjinit": "Një zonë historike e njohur për trashëgiminë e saj kulturore dhe historinë e pasur.",
"Qyteti i Pogradecit": "Një qytet bregdetar i njohur për bukurinë natyrore dhe historinë e tij të pasur.",
"Krahinat e Shqipërisë": "Rajone që karakterizohen nga tradita, zakone dhe veçoritë kulturore të veçanta, si veriu, jugi dhe qendra.",
"Festa e Shën Marina": "Një festë popullore që kremton shenjtoren Shën Marina, e cila ka rëndësi në traditën fetare të shqiptarëve.",
"Pasuria e Bujqësisë në Shqipëri": "Zhvillimi dhe trashëgimia e kulturës bujqësore shqiptare që ka formuar jetën e fshatarëve shqiptarë.",
"Përpunimi i leshit": "Një zeje tradicionale që ka mbajtur rëndësi të madhe në ndërtimin e veshjeve dhe sendeve të tjera.",
"Ushqimi i veriut": "Pjatat dhe gatimet tradicionale që janë tipike për zonat veriore të Shqipërisë.",
"Teza e Shën Koli": "Një vend i rëndësishëm historik dhe fetar në Shqipëri, ku ndodhet një nga kishat më të vjetra.",
"Rrethinat e Vlorës": "Një rajon me pasuri natyrore dhe një histori të pasur që ka luajtur një rol të rëndësishëm në zhvillimin e Shqipërisë.",
"Monumentet e Kukësit": "Vlera historike dhe kulturore të qytetit të Kukësit, që ka qenë një nga qendrat më të rëndësishme të Shqipërisë.",
"Festa e Pranverës": "Një festë që shënon ardhjen e pranverës dhe është një ngjarje e rëndësishme për shqiptarët.",
"Tradita e Gjirokastrës": "Kultura dhe zakonet e qytetit të Gjirokastrës, i njohur për arkitekturën dhe historinë e tij.",
"Monumenti i Kastriotëve": "Një memorial që përkujton pasurinë historike të familjes Kastrioti dhe ndikimin e saj në Shqipëri.",
"Vallëzimi i Shkodrës": "Një lloj vallëze tradicionale që përshkruan zakonet dhe histori të popullit të Shkodrës.",
"Mbishkrimi i Onufrit": "Një mbishkrim i gjetur në qytetin e Vlorës që përmban informacion të rëndësishëm historik dhe fetar.",
"Qyteti i Sarandës": "Një qytet bregdetar në jug të Shqipërisë, i njohur për bukuritë natyrore dhe turizmin.",
"Festivali i Teatrit Popullor": "Një ngjarje kulturore që shfaq punimet artistike të grupeve të teatrit popullor shqiptar.",
"Rituali i Pashkëve": "Kremtimi i festës së Pashkëve me rituale të veçanta që pasqyrojnë traditat fetare të shqiptarëve.",
"Kalaja e Gajtanit": "Një monument historik në veri të Shqipërisë, i njohur për ndihmën që i ka dhënë mbrojtjes nga pushtuesit.",
"Kultura e Kosovës dhe Mitrovicës": "Pasuria kulturore dhe historike e Kosovës, një rajon i njohur për traditat dhe zakonit e tij të pasura.",
"Arkitektura e Shkodrës": "Vepra dhe stil i arkitekturës tradicionale të qytetit të Shkodrës që shpreh identitetin e kësaj zone.",
"Festa e Bajramit në Shqipëri": "Një nga festat më të rëndësishme për besimtarët myslimanë shqiptarë, e cila kremtohet në gjithë vendin.",
"Shkolla e Shën Raphailit": "Një shkollë historike dhe edukative që ka luajtur rol të rëndësishëm në zhvillimin e arsimit në Shqipëri.",
"Festa e Shën Marisë": "Një festë që kremton nderimin e Shën Marisë dhe është e shënuar me rituale dhe zakone fetare.",
"Rrethinat e Beratit": "Një rajon i njohur për pasurinë natyrore dhe historinë e tij të pasur që është e lidhur ngushtë me kulturën e qytetit të Beratit.",
"Rruga e Dukatës": "Një rrugë që kalon përmes qytetit të Dukatës dhe është e njohur për pasuritë natyrore dhe historike.",
"Kultura e Fierit": "Një trashëgimi kulturore dhe historike që ka ndikuar shumë në zhvillimin e qytetit dhe rajonit të Fierit.",
"Festa e Shën Gjonit": "Një festë që kremton shenjtorin Shën Gjon, një ngjarje e rëndësishme për besimtarët katolikë në Shqipëri.",
"Ritet e hënës së re": "Një ritual që pasqyron besimet dhe zakonet e popullsisë shqiptare për lidhjen e njeriut me natyrën.",
"Ritualet e Shën Valentinës": "Një festë dhe rituale të lidhura me Shën Valentin, që kanë rëndësi për qytetet shqiptare dhe popullsinë e re.",
"Biblioteka Kombëtare e Shqipërisë": "Një nga institucionet më të rëndësishme kulturore dhe edukative që ruan dhe pasuron trashëgiminë e kulturës shqiptare.",
"Xhamia e Gjirokastrës": "Një ndër monumentet fetare të qytetit të Gjirokastrës, e njohur për stilin dhe historinë e saj.",
"Festa e Shën Nikollës": "Një festë që kremton Shën Nikollën dhe është një ngjarje e rëndësishme në kulturën fetare të shqiptarëve.",
"Monumenti i Arbërit": "Një memorial që përkujton traditat dhe historinë e fiseve arbëreshe në Shqipëri.",
"Rrëfimi i dashurisë": "Një lloj tregimi që pasqyron historitë e dashurisë dhe lidhjeve shoqërore në jetën e shqiptarëve.",
"Ballokume": "Një ëmbëlsirë tradicionale shqiptare e përgatitur me miell misri dhe sheqer, karakteristike për veriun e Shqipërisë.",
"Byrek me Mish": "Pjatë tradicionale me petë të mbushura me mish të grirë dhe erëza, e shpeshtë në shumë rajone të Shqipërisë.",
"Fërgesë": "Pjatë tradicionale e përgatitur me djathë, speca dhe domate, që është e njohur në jug të Shqipërisë.",
"Jufkë": "Petë e hollë dhe e shkrifët që përdoret për përgatitjen e byrekëve, piteve dhe ushqimeve të tjera tradicionale.",
"Trilece": "Ëmbëlsirë e njohur me shtresa të ndryshme kremi, përgatitur shpesh në Shqipërinë jugore.",
"Speca të mbushura": "Speca të mbushura me oriz, mish dhe erëza, një pjatë e njohur në shumë rajone shqiptare, veçanërisht në jug.",
"Shtriga": "Një ëmbëlsirë e bërë me brumë të thjeshtë dhe sheqer, që shërbehet shpesh në veri të Shqipërisë.",
"Qofte": "Topa të vegjël mishi të grirë, të skuqur ose të pjekur, që janë pjesë e kuzhinës tradicionale shqiptare.",
"Tava e Dajti": "Pjatë tradicionale nga veriu i Shqipërisë, e përgatitur me mish dhe perime, e njohur për shijen e saj karakteristike.",
"Shurup i grurit": "Një pije tradicionale që bëhet nga gruri dhe sheqeri, e përdorur shpesh në zona të ndryshme të Shqipërisë.",
"Fërgesa e Tiranës": "Një pjatë tradicionale që përfshin mish të pjekur, perime dhe djathë, karakteristike për Tiranën.",
"Shallotë me misër": "Pjatë që përgatitet me misër dhe shallotë, e zakonshme në rajonin e Myzeqesë.",
"Skamë": "Ushqim që përgatitet me mish të grirë, perime dhe oriz, që është i njohur në krahinat e jugut të Shqipërisë.",
"Qebapa": "Një ushqim i përbërë nga mish i grirë, i përgatitur në formë të gjatë dhe i skuqur, i shijshëm dhe i zakonshëm në veriun e Shqipërisë.",
"Tavë me patate": "Pjatë tradicionale që përgatitet me patate dhe mish, e njohur në shumë qytete të Shqipërisë.",
"Jani": "Pjatë e përgatitur nga veza dhe djathi i freskët, që është një shije tradicionale e rajonit të jugut.",
"Qumësht me miell misri": "Një pjatë tradicionale që përgatitet me qumësht dhe miell misri, e shijshme dhe shumë e zakonshme në zonat malore.",
"Jadele": "Ëmbëlsirë që përgatitet me sheqer dhe vezë, të karakterizuar nga shija e ëmbël dhe konsistenca e butë.",
"Njomë": "Një ëmbëlsirë tradicionale që bëhet me miell dhe mjaltë, e shijshme dhe tipike për krahinat jugore.",
"Maklube": "Një pjatë tradicionale me oriz, mish dhe perime, shumë e njohur në jug të Shqipërisë.",
"Kumbulla me sheqer": "Një ëmbëlsirë që bëhet me kumbulla dhe sheqer, shumë e njohur për shijen e saj të veçantë.",
"Tarator": "Supë e ftohtë me kos, gursh dhe perime të freskëta, shumë popullore në rajonin jugor të Shqipërisë.",
"Reçel boronicë": "Një reçel i bërë nga boronica dhe sheqer, që është një shije karakteristike për rajonin e veriut të Shqipërisë.",
"Fërgesë me mish": "Një pjatë tradicionale e përgatitur me mish të grirë dhe perime, që është e njohur në shumë zona të Shqipërisë.",
"Vezë e mbushur": "Një pjatë që përgatitet me vezë të mbushura me mish të grirë dhe oriz, shumë tipike për jugun.",
"Meze tradicionale": "Pjatë me një shumëllojshmëri antipastash që përfshin djathin, perimet dhe produktet e mishit.",
"Pilaf me mish dhe perime": "Pjatë tradicionale që përgatitet me oriz, mish dhe perime, dhe që është shumë e zakonshme në jug të Shqipërisë.",
"Krap i pjekur": "Pjatë tradicionale me krap të pjekur, e shijshme dhe e zakonshme në rajonin bregdetar të Shqipërisë.",
"Vaj ulliri": "Një produkt tradicional i Shqipërisë, shumë i përdorur në gatimet e përditshme për aromën dhe shëndetin.",
"Tullumbace": "Një ëmbëlsirë tradicionale që është e skuqur dhe zhytur në sherbet, karakteristike për gjithë Shqipërinë.",
"Kallamar i pjekur": "Pjatë tradicionale me kallamar të pjekur, që është e zakonshme në rajonin bregdetar të Shqipërisë.",
"Midhje të pjekura": "Pjatë popullore bregdetare e përgatitur me midhje të pjekura, tipike për jugun e Shqipërisë.",
"Qifqi": "Pjatë tradicionale e përgatitur me oriz dhe mish të grirë, që është e zakonshme në zonat malore.",
"Jufkë me gjalpë": "Petë e hollë e mbushur me gjalpë dhe sheqer, një ëmbëlsirë tradicionale e njohur në Shqipërinë jugore.",
"Çorba e kërpudhave": "Supë e përgatitur me kërpudha të freskëta, shumë e njohur në veriun e Shqipërisë.",
"Raki": "Pije alkoolike tradicionale e prodhuar nga frutat e ndryshme, shumë e popullarizuar në të gjitha krahinat e Shqipërisë.",
"Erëza e Elbasanit": "Kombinim i erëzave që përdoren për gatime të ndryshme, shumë tipike për rajonin e Elbasanit.",
"Shurup i luleshtrydheve": "Pije tradicionale e bërë me luleshtrydhe dhe sheqer, e shijshme dhe e zakonshme në jug.",
"Patate të pjekura me mish": "Pjatë tradicionale që përgatitet me patate dhe mish të pjekur, shumë e njohur në Shqipërinë qendrore.",
"Fasule me mish": "Një pjatë tradicionale e përgatitur me fasule dhe mish të grirë, shumë e zakonshme në Shqipërinë e Mesme.",
"Ushqimi i Karaburunit": "Një pjatë tradicionale që përfshin ushqime të pjekura dhe perime të freskëta, tipike për rajonin e Karaburunit.",
"Çorba e mishit": "Supë tradicionale e përgatitur me mish të freskët dhe perime të ndryshme, karakteristike për veri.",
"Shafran i Dajti": "Erëz që përdoret në shumë gatime tradicionale shqiptare, veçanërisht në zonën e Dajti.",
"Bakllava": "Ëmbëlsirë tradicionale e përgatitur me petë dhe arra, e zakonshme në të gjithë Shqipërinë.",
"Fruta të thata": "Kombinim i frutave të thata që përdoren si ëmbëlsirë apo si përbërës në disa gatime tradicionale.",
"Kastravec i turshuar": "Pjatë tradicionale që përgatitet me kastravec dhe kripë, shumë popullor në Shqipërinë e jugut.",
"Grurë i gatuar me mjaltë": "Pjatë tradicionale e përgatitur me grurë dhe mjaltë, një shije e zakonshme në zona malore.",
"Petulla me mjaltë": "Petulla e ngrohtë e shërbyer me mjaltë, që është një ëmbëlsirë tradicionale e njohur në jug.",
"Pashallëk i Elbasanit": "Një pjatë tradicionale e përgatitur me mish të pjekur, karakteristike për qytetin e Elbasanit.",
"Erëza e Dukatës": "Një kombinim i erëzave që përdoren për të aromatizuar gatimet tradicionale, shumë i njohur në Dukat.",
"Fshatarçik": "Një pjatë tradicionale që përgatitet me mish dhe perime, shumë tipike për zonat rurale të Shqipërisë.",
  "Tirana": "Kryeqyteti i Shqipërisë dhe qyteti më i madh, qendra administrative, kulturore dhe ekonomike e vendit.",
  "Shkodra": "Një qytet i njohur për historinë dhe kulturën e tij, ndodhet në veri të Shqipërisë dhe është i njohur për liqenin e Shkodrës.",
  "Durrësi": "Një nga qytetet më të vjetra dhe më të rëndësishme të Shqipërisë, me një histori të pasur dhe një port të madh detar.",
  "Vlorë": "Qyteti i njohur për bregdetin dhe historinë e tij, i lidhur ngushtë me shpalljen e Pavarësisë së Shqipërisë.",
  "Fier": "Një qytet industrial dhe bujqësor në jug të Shqipërisë, i njohur për industrinë e naftës dhe prodhimin e produkteve bujqësore.",
  "Elbasan": "Një qytet industrial dhe historik, i njohur për kalatën e tij dhe për rolin që ka luajtur gjatë periudhës osman.",
  "Korca": "Një qytet i njohur për klimën e tij të ftohtë dhe kulturën, si dhe për traditat e pasura, duke përfshirë muzikën dhe artizanatin.",
  "Berati": "Një qytet i quajtur 'Qyteti i njëmijë dritareve', i njohur për arkitekturën e tij të veçantë dhe kalatën e njohur.",
  "Gjirokastra": "Një qytet historik i njohur për arkitekturën e saj karakteristike, duke përfshirë shtëpitë e lashta dhe kalatën.",
  "Saranda": "Një qytet bregdetar në jug të Shqipërisë, i njohur për plazhet e tij të bukura dhe për afërsinë me ishujt e Jonit.",
  "Pogradec": "Një qytet i bukur në bregun e liqenit të Pogradecit, i njohur për turizmin dhe natyrën e tij të mrekullueshme.",
  "Kavaja": "Një qytet në jug të Tiranës, i njohur për bujqësinë dhe afërsinë me kryeqytetin.",
  "Vau i Dejës": "Një qytet i vogël i njohur për liqenin e tij dhe mundësitë për turizëm.",
  "Kamza": "Një qytet pranë Tiranës, i njohur për zhvillimin e shpejtë urban dhe për banorët që kanë origjinë nga qytetet e tjera.",
  "Mat": "Një qytet në veri të Shqipërisë, i njohur për historinë e tij dhe për monumentet natyrore.",
  "Kruja": "Një qytet historik në Shqipërinë qendrore, i njohur për kalatën dhe si qendër e rezistencës kundër osmanëve, veçanërisht nga Skënderbeu.",
  "Shijaku": "Një qytet në perëndim të Shqipërisë, i njohur për traditat bujqësore dhe peshkimin.",
  "Lushnja": "Një qytet në jug të Shqipërisë, i njohur për prodhimin e bujqësisë dhe industria ushqimore.",
  "Vora": "Një qytet afër Tiranës, i njohur për zhvillimin e infrastrukturës dhe ndërtimin e rezidencave.",
  "Rrogozhina": "Një qytet i njohur për bujqësinë dhe për pozicionin e tij strategjik në juglindje të Shqipërisë.",
  "Përmet": "Një qytet i njohur për natyrën e tij të bukur, i vendosur në luginën e Vjosës.",
  "Tepelenë": "Një qytet historik dhe strategjik i njohur për luftërat dhe betejat e shumta gjatë periudhës osmane.",
  "Cakran": "Një qytet në jug të Shqipërisë, i njohur për industrinë e naftës.",
  "Klos": "Një qytet i njohur për pasuritë natyrore dhe monumentet e lashta.",
  "Rashbull": "Një qytet i vogël i njohur për zhvillimin e turizmit dhe natyrën e tij malore.",
  "Bajkaj": "Një qytet në jug të Shqipërisë, i njohur për kalatën dhe traditat kulturore.",
  "Zall-Bastar": "Një qytet në veri të Shqipërisë, i njohur për natyrën e tij malore dhe lidhjet me historinë e lashtë.",
  "Përmet": "Një qytet i njohur për traditat kulturore dhe natyrën e tij të paprekur.",
  "Shushicë": "Një qytet i njohur për bukurinë natyrore dhe aktivitetet turistike.",
  "Kavajë": "Një qytet i njohur për mundësitë për zhvillimin e turizmit dhe natyrën e tij të bukur.",
  "Thumanë": "Një qytet i njohur për prodhimin e bujqësisë dhe zhvillimin urban.",
  "Ballsh": "Një qytet i njohur për industrinë e naftës dhe mundësitë për zhvillimin e turizmit.",
  "Nivica": "Një qytet në jug të Shqipërisë, i njohur për natyrën dhe monumentet e tij historike.",
  "Llixha": "Një qytet bregdetar, i njohur për plazhet e tij dhe mundësitë për turizëm.",
  "Bistricë": "Një qytet i njohur për natyrën malore dhe mundësitë për ecje dhe aktivitete në natyrë.",
  "Fushë-Krujë": "Një qytet i njohur për pasuritë e tij natyrore dhe historinë e tij të lashtë.",
  "Zajzë": "Një qytet i njohur për mundësitë për zhvillim dhe turizëm.",
  "Kaninë": "Një qytet i njohur për kalatën dhe historinë e tij të pasur kulturore.",
  "Gjergjan": "Një qytet i njohur për pasuritë natyrore dhe për traditat kulturore.",
  "Gajtan": "Një qytet i njohur për zhvillimin e turizmit dhe aktivitetet historike.",
  "Qafa e Shtamës": "Një qytet në veri të Shqipërisë, i njohur për bukuritë natyrore dhe zhvillimin turistik.",
  "Cakran": "Një qytet i njohur për industrinë e naftës dhe zhvillimin e turizmit.",
  "Rrëza": "Një qytet në jug të Shqipërisë, i njohur për natyrën dhe mundësitë për ecje në male.",
  "Gjakovë": "Një qytet historik, i njohur për lidhjet e tij me kulturën dhe historinë shqiptare.",
  "Kosovë": "Një qytet i njohur për zhvillimin e turizmit dhe natyrën e pasur malore.",
  "Ura e Vajzeve": "Një qytet i njohur për pasuritë natyrore dhe arkitekturën e tij historike.",
  "Vladimire": "Një qytet bregdetar i njohur për plazhet dhe turizmin.",
  "Koplik": "Një qytet i njohur për kalatën dhe mundësitë për zhvillim turistik.",
  "Rrëza": "Një qytet i njohur për historinë e tij dhe natyrën malore.",
  "Kamaj": "Një qytet i njohur për mundësitë për zhvillimin e turizmit dhe për traditat e tij kulturore.",
  "Përmet": "Një qytet historik dhe natyror i njohur për burimet e tij termale dhe bukuritë natyrore.",
  "Vashtemi": "Një qytet i njohur për zhvillimin e turizmit dhe për traditat kulturore.",
  "Himarë": "Një qytet bregdetar i njohur për plazhet dhe natyrën e bukur.",
  "Lëpushë": "Një qytet në jug të Shqipërisë, i njohur për mundësitë për turizëm dhe natyrën e paprekur.",
  "Vora": "Një qytet i njohur për zhvillimin e infrastrukturës dhe mundësitë për zhvillim urban.",
  "Tropojë": "Një qytet i njohur për natyrën dhe mundësitë për zhvillim turistik.",
  "Nikaj": "Një qytet i njohur për pasuritë natyrore dhe traditat e tij kulturore.",
  "Maliq": "Një qytet historik, i njohur për kalatën dhe pasuritë natyrore.",
  "Bajkaj": "Një qytet i njohur për pasuritë natyrore dhe monumentet historike.",
  "Vau i Dejës": "Një qytet i vogël i njohur për liqenin e tij dhe mundësitë për turizëm.",
  "Tragjas": "Një qytet i njohur për mundësitë për zhvillimin e bujqësisë dhe peshkimin.",
  "Selenicë": "Një qytet i njohur për industrinë dhe zhvillimin bujqësor.",
  "Saranda": "Një qytet i njohur për plazhet dhe traditat bregdetare."

};

const searchableData = Object.entries(data).map(([title, content]) => ({ title, content }));
